include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    avoid_catches_without_on_clauses: false
    public_member_api_docs: true
    use_super_parameters: true

analyzer:
  exclude:
    - test/.test_coverage.dart
  language:
    strict-casts: true
    strict-raw-types: true