include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    package_api_docs: true
    prefer_single_quotes: true
    avoid_catches_without_on_clauses: false

analyzer:
  exclude:
    - test/.test_coverage.dart
  language:
    strict-casts: true
    strict-raw-types: true
