name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 4.0.0
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  characters: ^1.3.0
  meta: ^1.9.1
  intl: ^0.18.1
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
  coverage: ^1.6.3
  mockito: ^5.4.0
  analyzer: ^5.12.0

scripts: scripts.yaml
