name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 1.2.1
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  characters: '>=1.0.0 <2.0.0'
  meta: '>=1.2.4 <2.0.0'
  intl: '>=0.16.1 <1.0.0'

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.15.7
  test_coverage: ^0.5.0
  mockito: ^4.1.3
