name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 2.1.1
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  characters: ^1.2.0
  meta: ^1.8.0
  intl: ^0.17.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  coverage: ^1.3.2
  mockito: ^5.2.0
  analyzer: ^4.1.0
