name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 3.1.0
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  characters: ^1.2.1
  meta: ^1.8.0
  intl: ^0.17.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
  coverage: ^1.6.1
  mockito: ^5.3.2
  analyzer: ^5.1.0
