name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 2.1.1
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  characters: '>=1.1.0 <2.0.0'
  meta: '>=1.3.0 <2.0.0'
  intl: '>=0.17.0 <1.0.0'
  collection: '>=1.15.0 <2.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
  coverage: ^1.0.3
  mockito: ^5.0.16
  analyzer: ^2.4.0
