name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 2.1.1
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  characters: '>=1.1.0 <2.0.0'
  meta: '>=1.3.0 <2.0.0'
  intl: '>=0.17.0 <1.0.0'
  collection: '>=1.15.0 <2.0.0'

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.16.8
  coverage: ^1.0.2
  mockito: ^5.0.3
  analyzer: 1.3.0
