name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 4.1.0
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  characters: '>=1.3.0 <2.0.0'
  meta: '>=1.9.0 <2.0.0'
  intl: '>=0.18.0 <1.0.0'
  collection: '>=1.17.1 <2.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
  coverage: ^1.6.3
  mockito: ^5.4.2
  analyzer: ^5.13.0

scripts: scripts.yaml
