name: screwdriver
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.
version: 5.10.0
homepage: https://github.com/birjuvachhani/screwdriver

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  characters: '>=1.3.0 <2.0.0'
  meta: '>=1.9.0 <2.0.0'
  intl: '>=0.18.0 <1.0.0'
  collection: '>=1.17.1 <2.0.0'
  web: '>=1.0.0 <2.0.0'
  path: '>=1.8.0 <2.0.0'
  universal_io: '>=2.2.0 <3.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  coverage: ^1.15.0
  mockito: ^5.5.0
  analyzer: ^7.5.5
  args: ^2.7.0

scripts: scripts.yaml

topics:
  - extensions
  - helpers
  - utility
  - utils