name: Coverage

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Tap Google's Dart formula repository
        run: brew tap dart-lang/dart
      - name: Install the Dart formula
        run: brew install dart
      - name: Install dependencies
        run: pub get
      - name: Activate Test Coverage
        run: pub global activate test_coverage
      - name: Generate Code Coverage
        run: pub global run test_coverage
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info