name: Publish on pub.dev

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tap Google's Dart SDK
        run: brew tap dart-lang/dart
      - name: Install Dart SDK
        run: brew install dart
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test
      - name: Format code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true