name: Publish on pub.dev

on:
  push:
    tags:
    # must align with the tag-pattern configured on pub.dev, often just replace
    #  with [0-9]+.[0-9]+.[0-9]+*
#     - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'
    # If you prefer tags like '1.2.3', without the 'v' prefix, then use:
    - '[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: ''
    # If you repository contains multiple packages consider a pattern like:
    # - 'my_package_name-v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test
      - name: Format code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Publish
        run: dart pub publish --force
#         uses: k-paxian/dart-package-publisher@v1.5.1
#         with:
#           credentialJson: ${{ secrets.CREDENTIAL_JSON }}
#           flutter: true
#           skipTests: true
