name: Code Quality

on:
  push:
    paths:
      - '**.dart'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get
      - name: Code Analysis
        run: dart analyze .
      - name: Code Formatting
        run: dart format --set-exit-if-changed .