name: Code Quality

on:
  push:
    branches:
      - main
    paths:
      - '**.dart'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    timeout-minutes: 5
    runs-on: macos-latest
    steps:
      - name: Tap Google's Dart formula repository
        run: brew tap dart-lang/dart
      - name: Install the Dart formula
        run: brew install dart
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get
      - name: Code Analysis
        run: dart analyze .
      - name: Code Formatting
        run: dart format --set-exit-if-changed .