name: Code Quality

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Analyzer
        run: dart analyze .
      - name: Dartfmt
        run: dart format --set-exit-if-changed --fix .