name: Stats

on:
  push:
    branches:
      - main
    paths:
      - '**.dart'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  update_stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Generate Stats
        run: dart scripts/stats.dart
      - name: Generate Extensions Docs
        run: dart scripts/extensions_docs_generator.dart -o EXTENSIONS.md
      - name: Update Stats on README.md
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: '*.md'
          message: '[CI] Update Stats & Extensions Docs'
          signoff: true