name: Tests & Coverage

on:
  push:
    branches:
      - main
    paths:
      - '**.dart'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  tests_and_coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Dart SDK
        run: |
          brew trust dart-lang/dart
          brew tap dart-lang/dart
          brew install dart
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
      - name: Install coverage package
        run: dart pub global activate coverage
      - name: Generate coverage report
        run: dart run coverage:test_with_coverage
      - name: Generate lcov file
        run: dart run coverage:format_coverage --packages=.dart_tool/package_config.json --lcov -i coverage/coverage.json -o coverage/lcov.info
      - uses: codecov/codecov-action@v7
        with:
          file: coverage/lcov.info